version: "3.8"

services:
  ansible:
    build:
      cache_from:
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ansible:${BUILD_TAG}
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ansible:${CI_DEFAULT_BRANCH}
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ansible:${CI_COMMIT_BRANCH}
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ansible:${BUILD_TAG}
